# version: 1
runtime: custom
vm: true
api_version: 1

manual_scaling:
  instances: 1

handlers:

- url: /(.*\.(html|css|js|png|jpg))
  static_files: public/\1
  upload: public/(.*\.(html|css|js|png|jpg))
